nvidia.api.key=${NVIDIA_API_KEY}
nvidia.api.url=https://integrate.api.nvidia.com/v1

langchain4j.open-ai.chat-model.base-url=${nvidia.api.url}
langchain4j.open-ai.chat-model.api-key=${nvidia.api.key}
langchain4j.open-ai.chat-model.model-name=meta/llama-3.1-70b-instruct

langchain4j.open-ai.embedding-model.base-url=${nvidia.api.url}
langchain4j.open-ai.embedding-model.api-key=${nvidia.api.key}
langchain4j.open-ai.embedding-model.model-name=nvidia/nv-embedqa-e5-v5